# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Estado',
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialGlobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 32, 937735))),
                ('fecha_inicio', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 32, 937823))),
                ('fecha_fin', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 32, 937902))),
                ('estado', models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado')),
            ],
            options={
                'verbose_name': 'Historial Globo',
                'db_table': 'historial_globo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=1000)),
                ('placa', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 32, 935325))),
                ('estado', models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado')),
            ],
            options={
                'verbose_name': 'Ocupacion',
                'db_table': 'ocupacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Piso',
                'db_table': 'piso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 32, 934160))),
                ('estado', models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado')),
                ('piso', models.ForeignKey(blank=True, db_column='piso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Piso')),
            ],
            options={
                'verbose_name': 'Posicion',
                'db_table': 'posicion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Usuario',
                'db_table': 'globo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='posicion',
            field=models.ForeignKey(blank=True, db_column='posicion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Posicion'),
        ),
        migrations.AddField(
            model_name='historialglobo',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Usuarios'),
        ),
    ]
