# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180920_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 40, 566855)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 40, 567002)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 40, 566938)),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 40, 562670)),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 13, 42, 40, 560657)),
        ),
    ]
