# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180920_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 38, 96348)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 38, 96581)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 38, 96512)),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 38, 90475)),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 38, 88108)),
        ),
    ]
