# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180920_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 41, 592817)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 41, 592968)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 41, 592900)),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 41, 588353)),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 15, 31, 41, 586711)),
        ),
    ]
