# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='interprete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('apellido', models.CharField(blank=True, max_length=300)),
                ('dni', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='locales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='localPlataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomlocal', models.CharField(blank=True, max_length=300)),
                ('nomplat', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.estado')),
                ('estadoper', models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.personal')),
                ('idInter', models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.interprete')),
                ('idlp', models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.localPlataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='suplp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300)),
                ('idloc', models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.locales')),
                ('idlop', models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.localPlataforma')),
                ('idpl', models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='tiposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='posicion',
            name='tipo',
            field=models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.tiposicion'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
